### ISSUE TITLE
安装最新的 appx 安装包时提示“因为已安装具有相同名称的不同程序包”

### ISSUE THREAD

**Issue by DCxDESIGN** [cotaku/Bibi-Release#1]
之前安装了第一版（？）的 appx （ https://github.com/cotaku/Bibi-Release/commit/09469b4d46a3d2bcbc348f1071c3e7490f7e379a#diff-4085d89185d76a0c7b9a003781fa6d8bff7d9ebc8a088eab1980ed91f92fb8f5 ），是通过安装包里直接导入签名证书后安装的，今天看到有新版（ https://github.com/cotaku/Bibi-Release/commit/e4891a60e94a0ef13236a0c1f7e84d1ec356e38c ）发布了，把安装包和独立出来的证书下载并导入之后，安装时提示：

“应用安装失败，错误消息: Windows 无法安装程序包 36699Atelier39.506979CA659D8_3.2.10.0_x64__rsj1xbqhgdnb8，因为已安装具有相同名称的不同程序包 36699Atelier39.506979CA659D8_3.2.10.0_x64__pke1vz55rvc1r。在安装之前，请删除程序包 36699Atelier39.506979CA659D8_3.2.10.0_x64__pke1vz55rvc1r。 (0x80073cf3)”

这是签名证书不同造成的现象吗？我是否一定需要把原程序包卸载了再重新安装？以后的新版发布也需要同样的操作吗？

非常感谢您能继续维护这个程序，期盼您的解答

**Comment by cotaku** [comment]
额，之前还没弄完（签名），主要是测试用的，你们动作太快了XD
现在差不多弄好了，需要先安装那个cer证书（Publisher="CN=Atelier39"，以后都用这个），你可能需要app卸载重装一下。

**Comment by cotaku** [comment]
P.S. 等正式发布的时候我会更新README详细说明的

**Comment by DCxDESIGN** [comment]
卸载后重新安装已成功，非常感谢
