### ISSUE TITLE
3.3 直播好像还是看不了

### ISSUE THREAD

**Issue by wangnick2017** [cotaku/Bibi-Release#100]
3.3 x60 windows11
换了几个直播间试了下，好像都不行，都是同一个错误显示视频流加载问题
<img width="521" alt="微信图片_20240503105823" src="https://github.com/cotaku/Bibi-Release/assets/33253388/d169dbfd-d284-4620-a96a-a4f41f70667d">

**Comment by cotaku** [comment]
重传了一下appx，麻烦重装再试一下

**Comment by wangnick2017** [comment]
现在可以了！多谢大佬！！
