### ISSUE TITLE
3.3.0arm版的最低系统版本要求好像还是16299

### ISSUE THREAD

**Issue by Qfsick** [cotaku/Bibi-Release#102]

**Comment by feiruixin** [comment]
没看见arm版啊？

**Comment by win98se** [comment]
> 没看见arm版啊？

被作者移除了，今早还有的，最低制版号的确还是16299

**Comment by cotaku** [comment]
又有问题没法打包ARM版了……

**Comment by win98se** [comment]
> 又有问题没法打包ARM版了……

https://github.com/cotaku/Bibi-Release/issues/73#issuecomment-2062836842 请问有试过这个方法了吗
我自己修改AppxManifest.xml（由Package.appxmanifest衍生）添加`Windows.Mobile`一行后重新打包，是可以正常安装、使用的

**Comment by cotaku** [comment]
是.NET Native Tool-Chain的问题

**Comment by cotaku** [comment]
手动打包签名了一个UWP_3.3.1.0_ARM.appx，麻烦装一下看看有没有问题。

**Comment by win98se** [comment]
> 手动打包签名了一个UWP_3.3.1.0_ARM.appx，麻烦装一下看看有没有问题。

可以，升级到你提供的3.3.1安装包后浏览、观看视频和直播目前都没问题

**Comment by Lumiamobile** [comment]
> UWP_3.3.1.0_ARM

如何获取更改的包

**Comment by win98se** [comment]
> > UWP_3.3.1.0_ARM
> 
> 如何获取更改的包

Releases一栏有啊？https://github.com/cotaku/Bibi-Release/releases/latest
