### ISSUE TITLE
收藏功能好像坏掉了

### ISSUE THREAD

**Issue by Jamesjili** [cotaku/Bibi-Release#11]
最新版3.2.12
所有的收藏功能均失效
错误提示代码-663
![IMG_20230918_183614_553](https://github.com/cotaku/Bibi-Release/assets/106306524/8a855cbd-9e02-4007-b353-b7d16610237d)
![IMG_20230918_183614_610](https://github.com/cotaku/Bibi-Release/assets/106306524/f05064ce-453b-479f-af81-c9bf9c40f999)

**Comment by DCxDESIGN** [comment]
x64 也能重现，收藏打不开

**Comment by cotaku** [comment]
663表示你需要重新登录一下

**Comment by DCxDESIGN** [comment]
> 663表示你需要重新登录一下

退出重新登录后还是报错

其中收藏报下图：
![image](https://github.com/cotaku/Bibi-Release/assets/48208459/c3c8f9b3-4d19-47e4-955c-861cfc37f070)

番剧和影视订阅继续报 663：
![image](https://github.com/cotaku/Bibi-Release/assets/48208459/f558559b-1e6e-4c60-aae7-4e936a673921)

**Comment by cotaku** [comment]
这不科学……要不卸载重装一下？

**Comment by bakabaka2333** [comment]
[https://github.com/cotaku/Bibi-Release/issues/13#issuecomment-1724733128](url)

**Comment by bakabaka2333** [comment]
https://github.com/cotaku/Bibi-Release/issues/13

**Comment by cotaku** [comment]
fixed in v3.2.13.0
