### ISSUE TITLE
可不可以增加原bilibili uwp的开屏图像与透明磁贴和动态磁贴功能

### ISSUE THREAD

**Issue by Lumiamobile** [cotaku/Bibi-Release#110]
可不可以增加原bilibili uwp的开屏图像与透明磁贴和动态磁贴功能

**Comment by Lumiamobile** [comment]
或者是刷视频的功能，但是工程量应该很大吧

**Comment by cotaku** [comment]
现在Windows11的开始菜单搞得都没有做动态磁贴的意义了……

**Comment by Lumiamobile** [comment]
> 现在Windows11的开始菜单搞得都没有做动态磁贴的意义了……

不过现在大多都还是在用win10吧

**Comment by Lumiamobile** [comment]
那另外两个功能呢

**Comment by cotaku** [comment]
你看我都特意没提，你还要特意再问一遍吗（逃

**Comment by lmcfemx** [comment]
> 你看我都特意没提，你还要特意再问一遍吗（逃

是...........................這樣嗎（wp10用戶哭哭qwq
