### ISSUE TITLE
希望增加顶部弹幕屏占比功能

### ISSUE THREAD

**Issue by wyh9462** [cotaku/Bibi-Release#111]
有个痛点功能希望作者大大考虑一下，目前客户端支持滚动弹幕屏占比功能，但是同等重要的顶部弹幕却不支持，以至于实际播视频的时候想看弹幕然后画面就被T型弹幕挡死了，就像这样：
![bb](https://github.com/cotaku/Bibi-Release/assets/15077343/ba8bc42a-0280-47ce-90af-d61c333c00d3)

目前网页端和手机端都会把滚动弹幕和顶部弹幕显示区域一起设置：
![image](https://github.com/cotaku/Bibi-Release/assets/15077343/c7d32a23-f308-404f-9c33-fd681d32c484)

能否考虑下加一个顶部弹幕屏占比，或者与滚动弹幕同步设置呢？

（如果可以的话屏占比配置能支持25%就更好了，经常觉得20%太少30%太多。

（还有弹幕字号如果能支持写数字就好了，经常觉得「大」太大而「中」又太小了，想调个中间值。

拜谢。

**Comment by cotaku** [comment]
- 可以把顶部弹幕和滚动弹幕的区域一并计算（之前默认顶部弹幕占比是75%）
- 占屏比设置从10%增减调整为5%增减
- 字号调整档位调整为7个（默认字号为24，增加一档为+4，减少一档为-2）

**Comment by wyh9462** [comment]
感谢作者。
