### ISSUE TITLE
带有分p的视频在信息页按ctrl+enter无法开始播放

### ISSUE THREAD

**Issue by wangnick2017** [cotaku/Bibi-Release#112]
3.3.1.0 win11 x64
如题，无分p的视频按ctrl+enter能正常播放，能否考虑让有分p的视频也支持该快捷键？

**Comment by cotaku** [comment]
可以是可以，但是默认播放1p么

**Comment by wangnick2017** [comment]
可以默认播放1p，也可以播放上次离开的位置，看大佬怎么方便怎么来吧

**Comment by cotaku** [comment]
fixed in v3.3.2.0
