### ISSUE TITLE
打开视频提示412错误，且修改质量都无用

### ISSUE THREAD

**Issue by win98se** [cotaku/Bibi-Release#12]
![image](https://github.com/cotaku/Bibi-Release/assets/11819816/1eb62998-c2d8-47cf-89bc-9bb63be8d7e5)
已登录，任何视频都这样，且质量会被定在MP4 8K，除了FLV之外都无法修改

**Comment by cotaku** [comment]
重新登录一下试试

**Comment by win98se** [comment]
尝试过了，这个错误信息是在登录同一个号的两个电脑上都显示的

**Comment by cotaku** [comment]
卸载重装一下试试……

**Comment by bakabaka2333** [comment]
https://github.com/cotaku/Bibi-Release/issues/13#issuecomment-1724733128

**Comment by cotaku** [comment]
fixed in v3.2.13.0
