### ISSUE TITLE
更新之后，追番、直播、收藏界面都出现了问题

### ISSUE THREAD

**Issue by komiblog** [cotaku/Bibi-Release#13]
收藏夹：
![image](https://github.com/cotaku/Bibi-Release/assets/102006886/649e8a49-e63e-4800-bd3b-359a7c99b8b7)
直播：
![image](https://github.com/cotaku/Bibi-Release/assets/102006886/9fc2f8b6-3d62-4b17-990d-a81a0675e563)
追番：
![image](https://github.com/cotaku/Bibi-Release/assets/102006886/19537168-4099-46df-a9c6-2c4791d182f0)
![image](https://github.com/cotaku/Bibi-Release/assets/102006886/6dd92720-3319-4c27-bb66-47fe4b6e780e)

**Comment by komiblog** [comment]
应该不是更新造成的，退回版本之后仍然有这个现象

**Comment by cotaku** [comment]
663表示你需要重新登录一下

**Comment by bakabaka2333** [comment]
> 663表示你需要重新登录一下


这个BUG好像是扫码登陆才会有
我用账户密码就没有

**Comment by bakabaka2333** [comment]
扫码登陆
![Snipaste_2023-09-19_11-26-09](https://github.com/cotaku/Bibi-Release/assets/45543164/dd7c2525-294b-47ef-b01b-4a666dda8ffa)
![Snipaste_2023-09-19_11-26-17](https://github.com/cotaku/Bibi-Release/assets/45543164/7015be78-c999-4c11-a605-0c879e9f872d)
![Snipaste_2023-09-19_11-26-25](https://github.com/cotaku/Bibi-Release/assets/45543164/c5ff3fa9-16e4-44b9-a3bb-cff2cfa3a8f2)
![Snipaste_2023-09-19_11-26-32](https://github.com/cotaku/Bibi-Release/assets/45543164/b451c187-77c6-49e7-8d49-97c17613679b)
![Snipaste_2023-09-19_11-28-03](https://github.com/cotaku/Bibi-Release/assets/45543164/b3b5be9c-4d64-4576-8b83-33863630e56b)

**Comment by bakabaka2333** [comment]
账户密码登录
![Snipaste_2023-09-19_11-31-04](https://github.com/cotaku/Bibi-Release/assets/45543164/62e28a7c-1b0b-4244-a88c-a85761622424)
![Snipaste_2023-09-19_11-31-10](https://github.com/cotaku/Bibi-Release/assets/45543164/5aa7a502-057c-4422-a972-4d6f72d2f971)
![Snipaste_2023-09-19_11-31-32](https://github.com/cotaku/Bibi-Release/assets/45543164/0e0dbf81-6c53-4935-a0b2-033e58055109)
![Snipaste_2023-09-19_11-32-14](https://github.com/cotaku/Bibi-Release/assets/45543164/e12cd815-a734-4f5f-9454-b1c33ed2341b)
![Snipaste_2023-09-19_11-32-32](https://github.com/cotaku/Bibi-Release/assets/45543164/b29665dc-8d99-470d-80f9-f4c611ae048c)

**Comment by cotaku** [comment]
> > 663表示你需要重新登录一下
> 
> 这个BUG好像是扫码登陆才会有 我用账户密码试了下就没有
> 
> 我这边是扫码登陆 把下面关注云电视点掉 就出现了这种情况

那我知道哪里出问题了，看看能不能修好……

**Comment by komiblog** [comment]
我复现了一下，确实是账号密码登录和扫描登录的问题，用账号密码登录，一切就正常了

**Comment by paperclouds3650** [comment]
我这里用密码登录会显示账户异常建议更改密码（更改后仍提示），只能用扫码登录

**Comment by cotaku** [comment]
fixed in v3.2.13.0
