### ISSUE TITLE
海外视频加速失效

### ISSUE THREAD

**Issue by zheng386** [cotaku/Bibi-Release#135]
打开番剧之后显示错误如图
![image](https://github.com/user-attachments/assets/ab1092c6-3ee6-4c8e-9ea3-3bda9da29fad)

**Comment by zheng386** [comment]
arm架构
系统信息如下，IP日本
![image](https://github.com/user-attachments/assets/8f2370ee-bb82-4473-914e-449b77631699)

**Comment by cotaku** [comment]
已恢复
