### ISSUE TITLE
动态更新只能回溯到一星期前

### ISSUE THREAD

**Issue by weng1277** [cotaku/Bibi-Release#139]
翻看动态更新发现，历史更新只能看到7月30日（8月5日查看），之前的更新无法加载
![image](https://github.com/user-attachments/assets/718c759d-a76e-4b8a-9ef7-fde0cf678a5f)

**Comment by cotaku** [comment]
首页的动态有最大数限制，可以进“关注动态”页面继续加载

**Comment by weng1277** [comment]
唔~明白了（
谢谢大大
