### ISSUE TITLE
更新到最新版本后获取最新动态失败

### ISSUE THREAD

**Issue by Louis0168** [cotaku/Bibi-Release#14]
在更新到最新版本3.2.12.0之后，拉取最新动态失败，显示请求被拦截，报错代码412，具体情况如下图所示
![屏幕截图 2023-09-20 092618](https://github.com/cotaku/Bibi-Release/assets/40681587/0a66af4c-c1f4-4ac3-a349-a40fc27f8e45)

**Comment by bakabaka2333** [comment]
https://github.com/cotaku/Bibi-Release/issues/13

**Comment by cotaku** [comment]
fixed in v3.2.13.0
