### ISSUE TITLE
试图播放要求实名才能观看的直播间时毫无反应，没有提示，仅显示“分析视频地址……失败”

### ISSUE THREAD

**Issue by win98se** [cotaku/Bibi-Release#142]
如题
![image](https://github.com/user-attachments/assets/9245c612-edca-47c9-86aa-c443385c2747)

例子：https://live.bilibili.com/598192

作为参考，在网页版提示如下：
![image](https://github.com/user-attachments/assets/b56bafe0-f50a-4dd5-b2b3-cd17478c403a)

**Comment by cotaku** [comment]
现在还有这个问题吗？我刚才逛了一下gamer区还没发现不给看的

**Comment by win98se** [comment]
> 现在还有这个问题吗？我刚才逛了一下gamer区还没发现不给看的

这个直播间后来没有实名要求了，观看其直播也正常了，目前还没遇到第二个有类似情况的直播间
因为属于极偶然事件，所以这个issue我先关
