### ISSUE TITLE
Xbox上的直播画面显示不完全

### ISSUE THREAD

**Issue by a516127341** [cotaku/Bibi-Release#151]
今天xbox上更新之后直播画面显示不对了，1920×1080就只有正常画面的四分之一，但是看视频1920×1080就是正常填满屏幕的

**Comment by cotaku** [comment]
能发个图看一下么

**Comment by a516127341** [comment]
> 能发个图看一下么

![EEU)LU73TYETA69$XJSQL1](https://github.com/user-attachments/assets/061170ca-63f6-4286-9232-2a10b73cf1d3)
![GHK469)U2WBRM6WLIT{ 3PS](https://github.com/user-attachments/assets/195db7df-1842-4ebf-b8d3-8655a9a3ac72)

**Comment by a516127341** [comment]
![71MSS103`L37~ 0I0A3HI](https://github.com/user-attachments/assets/df4d9a6b-e830-4443-a20b-52bf99f9490e)
看视频倒是没问题

**Comment by cotaku** [comment]
好的，我研究一下怎么回事，希望我的古董xbox还能启动……

**Comment by a516127341** [comment]
> 好的，我研究一下怎么回事，希望我的古董xbox还能启动……

辛苦了

**Comment by cotaku** [comment]
v3.3.4.0修复
