### ISSUE TITLE
不想在个人空间显示播放量，这样对我来说不美观

### ISSUE THREAD

**Issue by 12345xinkai** [cotaku/Bibi-Release#153]
如图![image](https://github.com/user-attachments/assets/dbcde44a-e5f7-4cbd-98bf-8b3c360ced1c)

**Comment by cotaku** [comment]
在网站的个人空间也会看到吧……

**Comment by 12345xinkai** [comment]
对，但要有设定，是否有播放量

**Comment by win98se** [comment]
那建议就在选项中做个开关吧

**Comment by cotaku** [comment]
![image](https://github.com/user-attachments/assets/6b5a0823-aead-4118-9933-4c5859f32d36)

**Comment by win98se** [comment]
@12345xinkai 3.3.4中可以开启以上选项了，你也检查一下

**Comment by cotaku** [comment]
v3.3.4.0修复
