### ISSUE TITLE
up主页打不开

### ISSUE THREAD

**Issue by WaSYee** [cotaku/Bibi-Release#155]
如图，从视频页点击up用户名进入主页
![7773f53fb72a38c9af122a44345973d3](https://github.com/user-attachments/assets/a65a0316-0424-4ebe-a236-5c863e74b294)
则不显示内容并显示风控校验失败，报错352
<img width="1280" alt="{BE32DF3F-69C3-429a-84A7-20960C9A8545}" src="https://github.com/user-attachments/assets/f6470186-35e3-48e6-9602-a7c1909c0413">
从合集名点进去
![d1bd6fd6dfd314cff42b23e60ff7b93c](https://github.com/user-attachments/assets/dafe8da6-3f48-4d85-81a0-32db3211ea00)
同样报错但能显示，是否加载完全未测试
<img width="1280" alt="{24D427FD-274D-4923-92D7-60CC72FD0AC3}" src="https://github.com/user-attachments/assets/5c601893-a9d0-4db2-97dc-00bb299e04d8">
经测试x64版v3.3.3.0仍然存在这个问题

**Comment by win98se** [comment]
重新登录

**Comment by WaSYee** [comment]
方法有用，已解决，感谢
