### ISSUE TITLE
在登录情况下进入专栏是未登录状态

### ISSUE THREAD

**Issue by WaSYee** [cotaku/Bibi-Release#156]
在登录状态下，从任何入口点进任何专栏，都是未登录状态
<img width="1280" alt="{C1935251-A4D8-44be-B188-F38DFB624B11}" src="https://github.com/user-attachments/assets/72de2c64-145f-4a94-9f3d-24c1ca0d1861">
如图↑
那个登录按钮，点进去走了登录流程后（哔哔本体已是登录状态），显示仍然是未登录状态。重新进专栏也一样

**Comment by cotaku** [comment]
密码登录还是扫码登陆？

**Comment by WaSYee** [comment]
登录软件本体用的是密码，图中测试专栏用的是扫码

**Comment by WaSYee** [comment]
神奇速报，刚才为了确认哔哔本体登录方式我退出登录了，再重新密码登录显示账号有风险，跳转网页端进行手机号验证后哔哔登录成功。
然后再点进专栏发现是登录状态了，个人怀疑和这次登出登入操作有关（之前的登录是在较早的版本上，一路覆盖更新到目前最新版都没有重登录过）

**Comment by cotaku** [comment]
因为专栏是内嵌浏览器，里面用的是登录后获取的cookie，可能不太稳定
