### ISSUE TITLE
个人空间中视频观看数与日期冲突

### ISSUE THREAD

**Issue by win98se** [cotaku/Bibi-Release#159]
如题，如果视频不是今年的，就无法显示完整的观看数，如下图
![image](https://github.com/user-attachments/assets/3f1527ba-47d0-478b-8283-9d46fa028912)

**Comment by win98se** [comment]
作为参考，要改善日期部分的话，可能可以做成像下图的搜索结果那样以`YYYY-MM-DD`来显示，`YYYY年MM月DD日HHmm`的确长多了
![image](https://github.com/user-attachments/assets/e4be38d1-d3e8-4a70-a421-637af8346c86)

**Comment by win98se** [comment]
在3.3.4中这个情况有改善了（虽然6位数或以上的观看数还是有可能难以显示完整），感谢
![image](https://github.com/user-attachments/assets/41043ff1-ef6e-4758-998a-c95e44d66120)
（这个issue我先关，不过如果作者有打算进一步修正可以开回来）

**Comment by cotaku** [comment]
可以在设置-界面&通知中调一下这项：
![image](https://github.com/user-attachments/assets/eb90ce93-c1e3-45dd-8a11-7248c4590c2a)
