### ISSUE TITLE
风险账号在进行网页验证后依旧无法登陆应用

### ISSUE THREAD

**Issue by SuanOrange** [cotaku/Bibi-Release#169]
风险账号在使用密码登陆时会出现异常，图一出现的界面不会跳转，关闭界面后才会跳转，然后界面变为图二登陆出现异常，验证后依旧无法登陆，之后如此循环
![屏幕截图 2024-09-13 090902](https://github.com/user-attachments/assets/018b129b-aea9-41c7-84b9-8a34a9da925c)
![屏幕截图 2024-09-13 091434](https://github.com/user-attachments/assets/4722432a-78d5-4ffb-b47b-d73fe7105dee)

**Comment by SuanOrange** [comment]
这个问题直接导致了无法使用账号密码进行登陆

**Comment by cotaku** [comment]
在网页端登录一下进行验证

**Comment by SuanOrange** [comment]
> 在网页端登录一下进行验证

我在网页端进行了登录验证，验证成功后网页端跳转了首页，但是应用内依旧是图二的样子，关闭后重新登陆又会循环图一图二的界面

**Comment by SuanOrange** [comment]
> 在网页端登录一下进行验证

或者把“扫码登陆时，点击专栏更新会显示鉴权失败，请联系账号组‘（https://github.com/cotaku/Bibi-Release/issues/146）这个问题修复了也可以

**Comment by cotaku** [comment]
> 或者把“扫码登陆时，点击专栏更新会显示鉴权失败，请联系账号组‘ #146 这个问题修复了也可以

这个很难修复，扫码登录用的是云视听的接口，用来访问其他接口会有很多限制

**Comment by SuanOrange** [comment]
> 在网页端登录一下进行验证

完整问题描述：风险账号在使用密码登陆时会出现异常，图一出现的界面不会跳转，关闭界面后才会跳转，然后界面变为图二登陆出现异常，验证后依旧无法登陆，之后如此循环

**Comment by DCxDESIGN** [comment]
https://github.com/cotaku/Bibi-Release/issues/72#issuecomment-1974263814

试试

**Comment by SuanOrange** [comment]
补充：3.3.4.0依旧有这个问题，但是3.3.2.0版本就没有这个问题

**Comment by cotaku** [comment]
可以改一下账号的密码之后再重新登录看看

**Comment by SuanOrange** [comment]
> 可以改一下账号的密码之后再重新登录看看

该方法无效，依旧出现上述问题，个人理解是出现“即将跳转到网页”界面后没有自动跳转，而是在点击取消后网页才会跳转，但是点击取消后会出现“登陆存在异常”，应用自动判定点击取消后本次验证失败，需要继续验证然后如此死循环

**Comment by cotaku** [comment]
这个不是应用判定的，是网站后台返回的结果，处理也只能在网页或者官方app上处理

**Comment by SuanOrange** [comment]
> 这个不是应用判定的，是网站后台返回的结果，处理也只能在网页或者官方app上处理

但是我个人在网页端和APP端都改过密码，依旧会出现上述情况，其他账号就没有这个问题

**Comment by SuanOrange** [comment]
我排除了多个设备同时登陆后在网页端更改了密码，依旧会出现上述情况

**Comment by cotaku** [comment]
但是目前想不到解决办法……

**Comment by SuanOrange** [comment]
> 但是目前想不到解决办法……

那就想想怎么解决专栏的“鉴权失败，请联系账户组”的问题吧（笑）

**Comment by cotaku** [comment]
fixed in v3.3.6.0
