### ISSUE TITLE
推荐和直播都无法使用了。

### ISSUE THREAD

**Issue by MTCCX** [cotaku/Bibi-Release#170]
![Image_1726194099345.jpg](https://github.com/user-attachments/assets/fb01e353-08e9-4cbe-9ab9-ff6c711110f5)

![Image_1726194101979.png](https://github.com/user-attachments/assets/469f95e7-8af4-4a19-8b9e-c4d956285582)

**Comment by qakcn** [comment]
#165 同样的问题，首页刷新困难，少的时候只有一两条甚至没有，多的时候也就一两页就刷不出来了。估计是B站那边限制了。

**Comment by everyonekas** [comment]
同样的问题，不过直播能看，只有首页不能推荐了

**Comment by qakcn** [comment]
最新版已解决，可以关闭了。

**Comment by MTCCX** [comment]
非常感谢作者修复。
