### ISSUE TITLE
“推荐”页面不显示内容或只能显示1~3个内容

### ISSUE THREAD

**Issue by Core-RJ** [cotaku/Bibi-Release#173]
![image](https://github.com/user-attachments/assets/fcbdd59f-8b14-4b43-b07b-3d06ef63abed)

处理器：Intel Core i3-1110g4
显卡：Intel UHD 730
系统版本号：19044.4894(windows 10 21H2)
登陆方式：扫码登陆

**Comment by Liuyiyang888888** [comment]
CPU型号：11th Gen Intel(R) Core(TM) i7-1160G7
登陆方式：密码登陆
“推荐”页面不显示内容或只能显示1~5个内容
+1

**Comment by MTCCX** [comment]
同样的问题，已经有一段时间了

**Comment by qakcn** [comment]
最新版已解决，可以关闭了。

**Comment by Core-RJ** [comment]
> 最新版已解决，可以关闭了。

感谢提醒！感谢作者！这就去下载最新版🌹
