### ISSUE TITLE
番剧索引页面失效，无法搜索番剧

### ISSUE THREAD

**Issue by hedsycssz** [cotaku/Bibi-Release#176]
无论完结动画还是连载动画，都搜索不到，显示一片空白
![屏幕截图 2024-09-29 114436](https://github.com/user-attachments/assets/6609bf20-ac22-4df3-bd28-b8f7faa2bf3c)
![屏幕截图 2024-09-29 114531](https://github.com/user-attachments/assets/e5b52e32-655e-40e6-822f-6aba22fa72b3)
还有就是首页推荐无法正常显示，分区页也无法正常显示
![屏幕截图 2024-09-29 114141](https://github.com/user-attachments/assets/1f4ee2a4-8bdb-44f6-8a55-42a72c53ad4d)
![屏幕截图 2024-09-29 114321](https://github.com/user-attachments/assets/3d734801-385c-413f-809f-d64e7619f397)

**Comment by qakcn** [comment]
我使用最新版3.3.4.0，首页推荐问题已修复，分区页面仍有问题，番剧页面没有问题。
