### ISSUE TITLE
关于视频推送

### ISSUE THREAD

**Issue by AndyChara-bili** [cotaku/Bibi-Release#188]
不知道是我的账户问题还是其他的什么原因，我还没看到别人问这个问题，但是很久了
在我用950xl使用本应用时，首页的个性化推荐基本上有很大问题
在三个月前，个性化推送的视频和我的账号内容无关，要刷新很久才能有一点有关联的视频
自从上个月（可能更早）以来，个性化推荐几乎不出视频了，虽然刷新可能会出一点点，但是还是不如原来
本情况只基于我在Lumia950xl伤使用的体验，其他平台的情况我不怎么知道

**Comment by cotaku** [comment]
ARM包最近都没有进行更新

**Comment by win98se** [comment]
你说到的问题其实就是#165，在3.3.4中解决了，不过这个版本才发布时难以制作手机版的ARM安装包
作者现在是刚刚发布了（https://github.com/cotaku/Bibi-Release/releases/download/v3.3.4.0/UWP_3.3.4.0_ARM.appx ；参考#180 和#186），请尝试

**Comment by AndyChara-bili** [comment]
挺好的 装上了 又给950续命了

Sent from Andy’s Lumia 950 XL
