### ISSUE TITLE
下载视频错误

### ISSUE THREAD

**Issue by llw1573** [cotaku/Bibi-Release#194]
在下载视频 BV16T421k7cp 时无论使用任何清晰度下载都会报错 如下:
`[0x80131620 ](6)Exception from HRESULT: 0x80072EFF`
使用BBDown进行下载后可以正常下载。在播放页面进行快速跳转亦未重现此错误。

**Comment by win98se** [comment]
是无法开始下载吗？从我这里点开始下载是没问题的，不过因为时长太长（2小时30分钟），我还没有试着下载到完

**Comment by llw1573** [comment]
是这个视频，在任何一个清晰度都会报这个错误。
下载1080p+时大约在2300MB附近开始报错，下载最低清晰度会在251MB卡住。

**Comment by llw1573** [comment]
确实是节点的问题，换了个网络环境能够正常下载了。感谢二位的帮助。
