### ISSUE TITLE
关于缓存页面的困扰

### ISSUE THREAD

**Issue by dnwyl2023** [cotaku/Bibi-Release#2]
UP你好 一直很喜欢这个软件 也很感谢您的分享  现在很多UP主不用分P来管理视频了 而用合集  这使得在下载后 本地页面很乱 可以根据合集合并或者自己可以合并么 多谢了

**Comment by dnwyl2023** [comment]
感谢 ！！！没事 我可以重新下载 但是希望可以管理合集 现在他们都不愿意分P了 可能 是为了更多的点赞和投币吧。。。。合集现在急需您的更新 再次感谢

**Comment by dnwyl2023** [comment]
> 下次会在本地视频页面增加按up主筛选的功能。合集的话因为以前下载的视频没有包含这个信息，即使支持也只能支持以后新下载的视频，老视频建议使用按名称排序或者直接使用导出功能在app外管理。

感谢 ！！！没事 我可以重新下载 但是希望可以管理合集 现在他们都不愿意分P了 可能 是为了更多的点赞和投币吧。。。。合集现在急需您的更新 再次感谢

**Comment by cotaku** [comment]
v3.2.12.0版已支持按UP主筛选本地视频。

**Comment by dnwyl2023** [comment]
> v3.2.12.0版已支持按UP主筛选本地视频。

666 非常感谢 爱你
