### ISSUE TITLE
建议支持AI字幕

### ISSUE THREAD

**Issue by win98se** [cotaku/Bibi-Release#200]
现在不少视频都已经有AI生成的字幕，但目前支持的字幕只有up主手动上载的那种，如果能支持AI字幕加入现有选项就更好了（但须特别注明字幕是AI生成的）

（这些AI字幕不是实时产生的，而是up主上载视频完成后就会产生这些字幕并作为该视频可选的字幕项）

据我所知，这些AI字幕都是可以使用小破站的API调出来的，yt-dlp和https://github.com/IndieKKY/bilibili-subtitle 都已经有下载它们的能力（虽然目前yt-dlp相关功能有大bug）

**Comment by cotaku** [comment]
会研究一下，技术上没问题的话会支持

**Comment by cotaku** [comment]
fixed in v3.3.5.0

**Comment by win98se** [comment]
证实3.3.5支持AI字幕了，感谢！
