### ISSUE TITLE
文字区中每条链接后的换行符异常消失

### ISSUE THREAD

**Issue by win98se** [cotaku/Bibi-Release#204]
如题（文字区指简介和评论）
实际上会消失的不只是换行符，还有空格，不过空格消失影响不大，而换行符消失就比较严重

作为参考：

![image](https://github.com/user-attachments/assets/423bdfde-9fc3-43d7-ba99-5f8be944a491)
![image](https://github.com/user-attachments/assets/e025d9ec-5b16-48b9-a74b-4dc351469655)
---
![image](https://github.com/user-attachments/assets/d6bed587-b682-419e-abe4-b82ea2535462)
![image](https://github.com/user-attachments/assets/3fa986b9-d145-48d7-bb3c-0c8658c38043)

**Comment by cotaku** [comment]
请提供一下相关视频的ID

**Comment by win98se** [comment]
> 请提供一下相关视频的ID

https://www.bilibili.com/video/BV1ip4y1A7rr/

**Comment by win98se** [comment]
3.3.5证实解决，谢谢
