### ISSUE TITLE
請教安裝問題

### ISSUE THREAD

**Issue by crazymark33** [cotaku/Bibi-Release#24]
請問是否可以在xbox上安裝呢？感謝你

**Comment by crazymark33** [comment]
非常感謝，我來研究看看，如果成功了一定來回報讓更多XBOX用戶能使用:D

**Comment by crazymark33** [comment]
剛剛已經安裝成功，程式內掃碼登入沒有問題，看了幾個4K的影片沒有出錯，之前在XBOX上還沒有可以正常運作觀看4K的B站第三方軟體，有一點想再請教一下作者，因為我第一次接觸開發者模式，請問在開發者模式中安裝的軟體(譬如這個BIBI)無法在一般模式下使用是嗎？感謝

**Comment by crazymark33** [comment]
剛剛再測試了一下其他功能，找了一些HEVC編碼安裝上XBOX但還是無法正常撥放4K影片，除此之外使用上大致都正常，非常感謝作者

**Comment by cotaku** [comment]
> 在開發者模式中安裝的軟體(譬如這個BIBI)無法在一般模式下使用是嗎？
这个我印象中好像有选项是可以的，不过现在手头也没有XBOX机器了，没法测试，你可能需要在网上查一下其他资料了。

> 找了一些HEVC編碼安裝上XBOX但還是無法正常撥放4K影片
我以前有台旧款的XBOX，那个时候4K就算勉强能播也很卡，但是现在新款XBOX的话至少播HEVC应该没问题……要么就是XBOX的硬解pipeline和PC不太一样需要调教（你可以启用软解试试），不过我现在反正也没法实际测试了，等哪天有机会再收台新机的时候再仔细研究（逃
