### ISSUE TITLE
安装完证书后无法安装appx

### ISSUE THREAD

**Issue by Ccyuan233** [cotaku/Bibi-Release#25]
<img width="1120" alt="image" src="https://github.com/cotaku/Bibi-Release/assets/147802683/8fd4c21d-47da-4eca-934c-700a5d51de86">

**Comment by cotaku** [comment]
证书安装的时候应该选择"本地计算机"而非"当前用户"

**Comment by Ccyuan233** [comment]
谢谢,他好用了
