### ISSUE TITLE
以下问题均是Windows10mobile端上出现的

### ISSUE THREAD

**Issue by gujiyeshi** [cotaku/Bibi-Release#28]
1 番剧无法正常播放（1080P和360P都提示无法加载）
2 直播间弹幕无法正常发送
3 数字藏品头像没有得到正常显示

感谢作者大大对UWPbilibili的贡献

**Comment by cotaku** [comment]
直播弹幕这块没办法了，整个后台验权机制都是独立的，好在普通视频弹幕还未受影响。
番剧我用非大会员账号看720p和360p都没发现问题，你说的是大会员限定的集数么？另外记得选MP4格式。
数字藏品头像是什么东东……

**Comment by gujiyeshi** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月31日(周二) 凌晨5:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cotaku/Bibi-Release] 以下问题均是Windows10mobile端上出现的 (Issue #28)




 
直播弹幕这块没办法了，整个后台验权机制都是独立的，好在普通视频弹幕还未受影响。
 番剧我用非大会员账号看720p和360p都没发现问题，你说的是大会员限定的集数么？另外记得选MP4格式。
 数字藏品头像是什么东东……

**Comment by cotaku** [comment]
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年10月31日(周二) 凌晨5:30 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [cotaku/Bibi-Release] 以下问题均是Windows10mobile端上出现的 (Issue #28) 直播弹幕这块没办法了，整个后台验权机制都是独立的，好在普通视频弹幕还未受影响。 番剧我用非大会员账号看720p和360p都没发现问题，你说的是大会员限定的集数么？另外记得选MP4格式。 数字藏品头像是什么东东…… — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

这没显示你的回复内容……

**Comment by gujiyeshi** [comment]
大哥，我不到为啥老给我邮件退回



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月1日(周三) 凌晨1:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cotaku/Bibi-Release] 以下问题均是Windows10mobile端上出现的 (Issue #28)




  
---原始邮件--- 发件人: @.&gt; 发送时间: 2023年10月31日(周二) 凌晨5:30 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [cotaku/Bibi-Release] 以下问题均是Windows10mobile端上出现的 (Issue #28) 直播弹幕这块没办法了，整个后台验权机制都是独立的，好在普通视频弹幕还未受影响。 番剧我用非大会员账号看720p和360p都没发现问题，你说的是大会员限定的集数么？另外记得选MP4格式。 数字藏品头像是什么东东…… — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
这没显示你的回复内容……

**Comment by gujiyeshi** [comment]
视频实在是发不出去


就是我用Windows10移动版打开哔哔，然后打开番剧，点击播放之后就提示无法播放





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月1日(周三) 凌晨1:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cotaku/Bibi-Release] 以下问题均是Windows10mobile端上出现的 (Issue #28)




  
---原始邮件--- 发件人: @.&gt; 发送时间: 2023年10月31日(周二) 凌晨5:30 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [cotaku/Bibi-Release] 以下问题均是Windows10mobile端上出现的 (Issue #28) 直播弹幕这块没办法了，整个后台验权机制都是独立的，好在普通视频弹幕还未受影响。 番剧我用非大会员账号看720p和360p都没发现问题，你说的是大会员限定的集数么？另外记得选MP4格式。 数字藏品头像是什么东东…… — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
这没显示你的回复内容……

**Comment by cotaku** [comment]
错误信息是什么？

**Comment by gujiyeshi** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月3日(周五) 下午4:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cotaku/Bibi-Release] 以下问题均是Windows10mobile端上出现的 (Issue #28)




 
错误信息是什么？

**Comment by DCxDESIGN** [comment]
我觉得题主应该考虑不要用邮件回复，直接在 GitHub 网页端或者手机客户端里回复。。

**Comment by gujiyeshi** [comment]
https://github.com/cotaku/Bibi-Release/assets/147959716/4f182232-f6e3-4bc0-a885-8dd9a5103622

**Comment by cotaku** [comment]
清晰度那里不要手选，直接MP4+自动可以解决大部分问题

**Comment by gujiyeshi** [comment]
依旧不行，我打算重装一下试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月9日(周四) 下午3:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cotaku/Bibi-Release] 以下问题均是Windows10mobile端上出现的 (Issue #28)




 
清晰度那里不要手选，直接MP4+自动可以解决大部分问题

**Comment by gujiyeshi** [comment]
Win10移动版还是不行

930试过了无法播放番剧，950也没法播，错误代码都是这个






(x86-64版不知为啥提示缺少签名装不上)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月9日(周四) 下午3:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cotaku/Bibi-Release] 以下问题均是Windows10mobile端上出现的 (Issue #28)




 
清晰度那里不要手选，直接MP4+自动可以解决大部分问题

**Comment by gujiyeshi** [comment]
错误
无法加载MP4视频:Unspecified error (Excep_FromHResult 0x80004005) aid=806763358_part=1_https=True_isLoggedIn=True host: http://xy222x136x90x139xy.mcdn.bilivideo.cn:4483


刚才图糊了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月9日(周四) 下午3:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cotaku/Bibi-Release] 以下问题均是Windows10mobile端上出现的 (Issue #28)




 
清晰度那里不要手选，直接MP4+自动可以解决大部分问题

**Comment by cotaku** [comment]
app设置里面启用“使用兼容播放器”试试

**Comment by gujiyeshi** [comment]
依旧无法加载，软解试过了也没啥用
可能是B站换端口了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月6日(周六) 中午12:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cotaku/Bibi-Release] 以下问题均是Windows10mobile端上出现的 (Issue #28)




 
app设置里面启用“使用兼容播放器”试试

**Comment by gujiyeshi** [comment]
还是不行，能试的都试了，开在诊断模式下番剧视频加载到300MB左右的时候就停止加载了


不过把视频下载还是可以播放的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月6日(周六) 中午12:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cotaku/Bibi-Release] 以下问题均是Windows10mobile端上出现的 (Issue #28)




 
app设置里面启用“使用兼容播放器”试试

**Comment by gujiyeshi** [comment]
对了，之前我不是反应直播没法发弹幕嘛，今天这个弹幕能发了(是真的能发出去了，我在up战士的弹幕板里看到我的弹幕了)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月31日(周二) 凌晨5:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cotaku/Bibi-Release] 以下问题均是Windows10mobile端上出现的 (Issue #28)




 
直播弹幕这块没办法了，整个后台验权机制都是独立的，好在普通视频弹幕还未受影响。
 番剧我用非大会员账号看720p和360p都没发现问题，你说的是大会员限定的集数么？另外记得选MP4格式。
 数字藏品头像是什么东东……
