### ISSUE TITLE
视频加载失败

### ISSUE THREAD

**Issue by kokodayo3256** [cotaku/Bibi-Release#29]
开启hevc后显示视频加载失败，针对应用的许可证检查失败，关闭hevc视频播放提示码率过低请在设置中打开hevc，还时不时有卡顿。hevc扩展已安装
![微信图片_20231031204624](https://github.com/cotaku/Bibi-Release/assets/149496400/ff41774e-e5bf-4852-bfa4-ba2907493810)

**Comment by cotaku** [comment]
hevc扩展从哪个渠道安装的？能查一下对应的PackageFamilyName么

**Comment by kokodayo3256** [comment]
我犯蠢了，没注意看下了个x86的，我换了个x64的就没问题了
