### ISSUE TITLE
“专栏更新”板块不能显示并报错

### ISSUE THREAD

**Issue by DCxDESIGN** [cotaku/Bibi-Release#30]
好像是从这两天开始的，点击专栏更新会报错：

![SShot-20231101-010008-ApplicationFrameHost](https://github.com/cotaku/Bibi-Release/assets/48208459/64d3adfa-2586-48fb-b37f-c5f86cb0f26e)

点击下方刷新或者重启程序都依然如此

**Comment by cotaku** [comment]
只是列表刷不出来么，"分区-专栏"的列表和文章本身能否显示？

**Comment by DCxDESIGN** [comment]
> 只是列表刷不出来么，"分区-专栏"的列表和文章本身能否显示？

分区 - 专栏 里面的推荐内容可以显示，点进去的文章也可以显示

**Comment by cotaku** [comment]
看了一下，这个功能好像已经在网页端消失了？可能原来的接口已经失效了，但是找不到最新的接口……

**Comment by DCxDESIGN** [comment]
> 看了一下，这个功能好像已经在网页端消失了？可能原来的接口已经失效了，但是找不到最新的接口……

诶这样吗。。太久不用网页端了。。所以现在是只有 视频更新 和 所有更新和动态都混在一起 的模式了吗

**Comment by cotaku** [comment]
你重新登录一下账号再试试……我这边试了一下好像没问题，就是这个接口用的cookie容易过期

**Comment by DCxDESIGN** [comment]
> 你重新登录一下账号再试试……我这边试了一下好像没问题，就是这个接口用的cookie容易过期

试了下，确实可以了。。但以前我长期保持登录的时候也没有遇到过这个问题。。不知道有没有什么办法未来可以避免【

anyway 感谢您❤

**Comment by cotaku** [comment]
这个接口就这样，在找到新接口替换之前只能忍忍了……

**Comment by DCxDESIGN** [comment]
> 这个接口就这样，在找到新接口替换之前只能忍忍了…… （顺便说下当前接口是 https://app.bilibili.com/x/feed/upper/article ）

明白了，那这个我就先关掉了
