### ISSUE TITLE
X86版本的哔哔还会有吗

### ISSUE THREAD

**Issue by 2858064995** [cotaku/Bibi-Release#32]
如题，由于本人有几台低功耗的古早电脑和平板，运行64位Windows实在是有些困难（低功耗凌动）所以之前是在1709的X86环境下使用商店的哔哔，但是现在哔哔暂不支持X86，虽然Windows11现在x64 only，但是我还是想咨询一下X86是否有适配计划。

**Comment by cotaku** [comment]
可以有，没做只是因为没想到真的有人还需要x86……下次更新会补上

**Comment by cotaku** [comment]
fixed in v3.2.14.0
