### ISSUE TITLE
无法关注UP主

### ISSUE THREAD

**Issue by Jamesjili** [cotaku/Bibi-Release#34]
关注UP主时提示服务器没有响应
![20231112_210920](https://github.com/cotaku/Bibi-Release/assets/106306524/338592ae-c205-4e30-bb5b-f85c206cb036)

**Comment by cotaku** [comment]
试了一下没问题，可能是间歇性的，再试试？

**Comment by Jamesjili** [comment]
又在不同网络条件下试了几次，还是不行
而且在手机端点应用内设置-高级选项-系统信息时会卡死

**Comment by cotaku** [comment]
fixed in v3.2.14.0
