### ISSUE TITLE
作者大大考虑做这种带弹幕的小窗播放吗？特别方便

### ISSUE THREAD

**Issue by kakukuka** [cotaku/Bibi-Release#37]
![image](https://github.com/cotaku/Bibi-Release/assets/153885121/5d7e827e-3ea8-4dd2-be9f-fd44215ed0f4)

**Comment by cotaku** [comment]
这个功能不就是：
![image](https://github.com/cotaku/Bibi-Release/assets/2822574/c06f34dd-f335-445a-86fe-68f929f33c1b)

**Comment by kakukuka** [comment]
这个逻辑好像不一样哎，而且经常出现一直卡在“正在获取播放地址”的现象，不能即点即开，不知道是不是我的问题

**Comment by cotaku** [comment]
因为这个窗口只是用来随便看一下，没有完整播放器的功能，如果认真看视频我还是选择进去全屏看（逃
