### ISSUE TITLE
【FEATURE】密码框显示字符

### ISSUE THREAD

**Issue by MSEDGE-WXZ** [cotaku/Bibi-Release#38]
登录界面的密码框没有开放显示字符功能，在某些特殊情况下（比如一不小心清空浏览器后台并且忘记密码时）或“密码比较长打错了一个字”时，比较麻烦。作者大大能否加入“显示密码字符”功能？非常感谢！！！！软件非常好，最喜欢下载视频的功能。
![image](https://github.com/cotaku/Bibi-Release/assets/154116904/58c13c31-579e-434e-a158-c55399cd62c5)
（原贴：密码忘了，翻到了加密的文件但是解不出来，在距离上课1分钟时写的帖子）
感谢作者！！！！！！！！！！！！！！！

**Comment by cotaku** [comment]
可以用app里的联系方式给我发个邮件，我会帮你下一步

**Comment by MSEDGE-COOL** [comment]
@cotaku 我更改了issue内容（原贴：密码忘了，翻到了加密的文件但是解不出来，在距离上课1分钟时写的帖子）

**Comment by cotaku** [comment]
可以

**Comment by cotaku** [comment]
fixed in 3.2.15.0
