### ISSUE TITLE
番剧索引功能失效，无法搜索番剧！

### ISSUE THREAD

**Issue by hedsycssz** [cotaku/Bibi-Release#40]
无论完结番还是连载番，全都显示空白，番剧索引功能失效了，作者大大快修复求求了！
![1](https://github.com/cotaku/Bibi-Release/assets/154669275/8e3503b1-ace1-48f0-b5c0-3ce7c22b022a)
![2](https://github.com/cotaku/Bibi-Release/assets/154669275/f8fcb576-4167-4fd7-9b91-9779af2a78f8)

**Comment by cotaku** [comment]
好像已经没问题了？
![image](https://github.com/cotaku/Bibi-Release/assets/2822574/79d50ee5-53cc-40d5-a6fe-efdf297944af)

**Comment by hedsycssz** [comment]
是的，好了，谢谢作者大大修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cotaku/Bibi-Release"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月17日(星期三) 上午8:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cotaku/Bibi-Release] 番剧索引功能失效，无法搜索番剧！ (Issue #40)





 
好像已经没问题了？
 image.png (view on web)

**Comment by hedsycssz** [comment]
上月开始又出现这个问题了，已经提交了问题单，麻烦尽快处理。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年1月17日(周三) 上午8:41
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cotaku/Bibi-Release] 番剧索引功能失效，无法搜索番剧！ (Issue #40)




 
好像已经没问题了？
 image.png (view on web)
