### ISSUE TITLE
请问更新之后的哔哔为什么没有新版播放页了？

### ISSUE THREAD

**Issue by ayakaxi** [cotaku/Bibi-Release#43]
如图所示，这是微软下载的uwp版播放页
![2B171D5365BF6947AC09CD2BE278DFAC](https://github.com/cotaku/Bibi-Release/assets/155423968/bd2cd731-b818-4766-b435-4ed5128467d5)
在这个版本设置里有一项叫做【使用新版播放页】的选项，如图
![E494401338704ECB0E3BF70F46DBB871](https://github.com/cotaku/Bibi-Release/assets/155423968/3e3a4100-9c39-4872-aaf3-4de82bf277d1)
而最近更新的版本并没有这个选项，请问是舍弃了这个功能，还是后续更新会加入呢？

**Comment by cotaku** [comment]
现在商店直接下载的本版已经被官方接手维护了，和这里的会越来越不同（逃

**Comment by ayakaxi** [comment]
原来如此

**Comment by ayakaxi** [comment]
原来如此
