### ISSUE TITLE
有没有可能将ARM的最低版本降为15035？

### ISSUE THREAD

**Issue by carrothu-cn** [cotaku/Bibi-Release#45]
感谢大佬还在坚持更新APP。
手上有个SurfaceRT2，Win10版本只能停留在15035了，看似和15063相差不大，不知实现难度大吗？

**Comment by cotaku** [comment]
![image](https://github.com/cotaku/Bibi-Release/assets/2822574/4979daad-7bbd-47ec-9971-b431e671c019)
估计不能手动指定版本号，而且有些必需接口只有在15063的SDK上才有，不然我可以直接降到14393（逃

**Comment by carrothu-cn** [comment]
感谢大佬回复，看来15035系统的确太过老旧了¯\_(ツ)_/¯

**Comment by DellZHackintosh** [comment]
可以强行降低版本要求，而且此应用可以在其上运行，接口那时候应该已经完备了。
把编译后的包拆开，改`AppxManifest.xml`里边的`TargetDeviceFamily`然后重打包加签名就可以了，虽然有些麻烦。

**Comment by carrothu-cn** [comment]
> 可以强行降低版本要求，而且此应用可以在其上运行，接口那时候应该已经完备了。
> 把编译后的包拆开，改`AppxManifest.xml`里边的`TargetDeviceFamily`然后重打包加签名就可以了，虽然有些麻烦。

感谢大佬提供思路，我尝试一下

**Comment by DellZHackintosh** [comment]
不过这边也是建议开发者 @cotaku  能够提供一个 ARM 版本包的呢~

**Comment by cotaku** [comment]
> 15035

对，我顺手改的
