### ISSUE TITLE
账号密码登录出现异常

### ISSUE THREAD

**Issue by Samuel-Knight** [cotaku/Bibi-Release#47]
![IMG_20240121_003441](https://github.com/cotaku/Bibi-Release/assets/55777323/6bba5bd8-c7db-4d7e-9de0-b176c83babaa)
v3.2.15.0 x64
扫码登录正常，账号密码登录会显示异常弹窗。

**Comment by cotaku** [comment]
一般出现这问题是被风控了，扫码能登上也行吧……

**Comment by Samuel-Knight** [comment]
> 一般出现这问题是被风控了，扫码能登上也行吧……

扫码确实没问题，这个被风控倒是头一次听到这个说法。

**Comment by Samuel-Knight** [comment]
> 一般出现这问题是被风控了，扫码能登上也行吧……

好的，之前以为是啥bug。
