### ISSUE TITLE
240129 晚间起，过审的稿件有极高比例无法查阅

### ISSUE THREAD

**Issue by DCxDESIGN** [cotaku/Bibi-Release#51]
目前没有找到规律，暂时只能举例子：

https://space.bilibili.com/8111543

如上这位用户的最新一个投稿，在网页版可以看到它的信息和链接地址如下图：

![image](https://github.com/cotaku/Bibi-Release/assets/48208459/00dd218f-b381-465a-9432-86444632188e)

而在软件内，可以在关注动态内看到这个投稿，但点进去后，标题的 BV 号就不对了，界面里也显示此稿件不存在，但评论区是能看的：

![image](https://github.com/cotaku/Bibi-Release/assets/48208459/b9d0ef60-c28f-4d10-8f2e-84ca39e3058b)

您可以关注一下这个帐号然后在动态里点进去看看，我这里还发现了别的几个稿件也有这个问题，都是今晚新投的，但又不是所有的新稿件都有这个问题【

**Comment by DCxDESIGN** [comment]
补充：晚间起过审的稿件几乎（十个里有八个以上）都会报错

**Comment by cotaku** [comment]
不同地方返回的BV号竟然不同，服了……

**Comment by 12345xinkai** [comment]
当我上传了很多视频，其中只有一个视频能正确显示bv号：aqo55的Super Mario 74 Ten Years After v3.74 - Course 12: Cliff of Time (Savestateless)，https://www.bilibili.com/video/BV1bx4y1Z7Ej
When I uploaded many videos, one only showed bvid correctly

以下是bv号偏移
bvid offsets below
juzcook的Mario Finds a Ghost Town // OMH (Part https://github.com/SocialSisterYi/bilibili-API-collect/pull/16): 正确：https://www.bilibili.com/video/BV1Lp421f7Wz ，错误：https://www.bilibili.com/video/BV1DT4C1G7Jh
shisyow的Another Generic 74EE Edit: Course 2 - Corona Virusvine (Savestateless)，正确：https://www.bilibili.com/video/BV1dK421y7Mc ，错误：https://www.bilibili.com/video/BV1hS4k1f7AX
N450 SMW Central的Häschen [hɛʃn̩] https://github.com/SocialSisterYi/bilibili-API-collect/issues/1 - Mission: Get Yosh，正确：https://www.bilibili.com/video/BV1WF4m1u7NK ，错误：https://www.bilibili.com/video/BV1fC4C1p7FZ
aqo55的Super Mario 74 Ten Years After v3.74 - Course 13: Sea Salt Peaks (Savestateless)，正确：https://www.bilibili.com/video/BV1MA4m1L7h7 ，错误：https://www.bilibili.com/video/BV1C24C1b74u
katze789的Box World [savestateless]，正确：https://www.bilibili.com/video/BV15y421a7fr ，错误：https://www.bilibili.com/video/BV1St4C117RY
Ozzie的STUPID XMAS BALLZ: MorningStorm64's Lost Souls (Savestateless)，正确：https://www.bilibili.com/video/BV1oJ4m1t7NQ ，错误：https://www.bilibili.com/video/BV1aA4y1k7cC
等等

**Comment by 12345xinkai** [comment]
> 不同地方返回的BV号竟然不同，服了……

超级bug super bug

**Comment by skdom2007** [comment]
目前旧版B站包括B漫安卓版app都存在看不了新视频新漫画的评论的问题，怀疑可能B站自己搞的鬼在强制清理旧版app

**Comment by DCxDESIGN** [comment]
另外补充一下：如果我用网页版上正确的 BV 号直接在 App 里进行搜索的话，可以出现稿件界面，但评论区无法读出，并且标题上的 AV 号也会不正确：

![image](https://github.com/cotaku/Bibi-Release/assets/48208459/0db27df2-468a-4f3c-8332-54b5e0126824)

**Comment by qakcn** [comment]
> 另外补充一下：如果我用网页版上正确的 BV 号直接在 App 里进行搜索的话，可以出现稿件界面，但评论区无法读出，并且标题上的 AV 号也会不正确：
> 
> ![image](https://private-user-images.githubusercontent.com/48208459/300708559-0db27df2-468a-4f3c-8332-54b5e0126824.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDI2MjMsIm5iZiI6MTcwNjYwMjMyMywicGF0aCI6Ii80ODIwODQ1OS8zMDA3MDg1NTktMGRiMjdkZjItNDY4YS00ZjNjLTgzMzItNTRiNWUwMTI2ODI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA4MTIwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MTI1YzNjOGYwYWI0Yzg5NDk0MGEwZjg3ZjUxOGY2NDYzOWY1NzEzNzIxNmE1NzIzNWUzNDYyMTlhZjQzZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jV_W0RHt5tQNQVijxEc8MgU2OEcH5qNuNTtfrThBvG0)

AV号的问题和我遇到的一样 #52 ，我是从关注列表里访问的。

**Comment by 12345xinkai** [comment]
> 不同地方返回的BV号竟然不同，服了……

希望找个人改代码来适应新视频

**Comment by 12345xinkai** [comment]
> > 不同地方返回的BV号竟然不同，服了……
> 
> 希望找个人改代码来让新视频适应这里

或者找一个靠谱的投诉平台

**Comment by 12345xinkai** [comment]
> > > 不同地方返回的BV号竟然不同，服了……
> > 
> > 
> > 希望找个人改代码来让新视频适应这里
> 
> 或者找一个靠谱的投诉平台

我在某猫投诉平台上投诉投稿产品难用

**Comment by DCxDESIGN** [comment]
> > > 希望找个人改代码来让新视频适应这里
> > 
> > 
> > 或者找一个靠谱的投诉平台
> 
> 我在某猫投诉平台上投诉投稿产品难用

……请问您在别人提的 issue 下面发什么神经？

这里是向开发者反馈问题的地方，开发者确认是 bug 了就等开发者之后更新进版就行，开发者不是商家你去国内消费平台投诉意义何在？

**Comment by cotaku** [comment]
fixed in [v3.2.16.0](https://github.com/cotaku/Bibi-Release/releases/tag/v3.2.16.0)

**Comment by DCxDESIGN** [comment]
> fixed in [v3.2.16.0](https://github.com/cotaku/Bibi-Release/releases/tag/v3.2.16.0)

这版好像是直接创建了个新的应用诶？不是覆盖原来的哔哔了，是把包名换了吗？

**Comment by DCxDESIGN** [comment]
以及标题栏现在好像不显示 BV 号了。。

**Comment by skdom2007** [comment]
> fixed in [v3.2.16.0](https://github.com/cotaku/Bibi-Release/releases/tag/v3.2.16.0)

是一个独立的应用是么

**Comment by skdom2007** [comment]
> > fixed in [v3.2.16.0](https://github.com/cotaku/Bibi-Release/releases/tag/v3.2.16.0)
> 
> 这版好像是直接创建了个新的应用诶？不是覆盖原来的哔哔了，是把包名换了吗？

完全独立应用，可以和之前那个共存

**Comment by cotaku** [comment]
> > fixed in [v3.2.16.0](https://github.com/cotaku/Bibi-Release/releases/tag/v3.2.16.0)
> 
> 这版好像是直接创建了个新的应用诶？不是覆盖原来的哔哔了，是把包名换了吗？

偷偷在商店里创建了个新应用，想看看能不能混进去重新上传一下，没注意本地打包的app名也给换了（逃

**Comment by cotaku** [comment]
> > 以及标题栏现在好像不显示 BV 号了。。
> 
> 同；另外，“复制视频链接”、“复制视频BV号”等功能依旧给出错误的BV号

因为现在AV号和BV号的转换关系不稳定了，而且有些老接口只返回AV号，所以标题栏不显示BV号的话就是不确定，现在只是紧急修复bug，等有空再研究如何正确获取BV号。

**Comment by DCxDESIGN** [comment]
> > > 以及标题栏现在好像不显示 BV 号了。。
> > 
> > 
> > 同；另外，“复制视频链接”、“复制视频BV号”等功能依旧给出错误的BV号
> 
> 因为现在AV号和BV号的转换关系不稳定了，而且有些老接口只返回AV号，所以标题栏不显示BV号的话就是不确定，现在只是紧急修复bug，等有空再研究如何正确获取BV号。

谢谢解答，不过既然“访问网页版”可以改成用 AV 号访问，那下一版如果暂时不能彻底搞定 BV 号的推算问题，“复制链接”是不是可以（暂时）改成 AV 号的链接【如果方便的话

**Comment by cotaku** [comment]
> > > > 以及标题栏现在好像不显示 BV 号了。。
> > > 
> > > 
> > > 同；另外，“复制视频链接”、“复制视频BV号”等功能依旧给出错误的BV号
> > 
> > 
> > 因为现在AV号和BV号的转换关系不稳定了，而且有些老接口只返回AV号，所以标题栏不显示BV号的话就是不确定，现在只是紧急修复bug，等有空再研究如何正确获取BV号。
> 
> 谢谢解答，不过既然“访问网页版”可以改成用 AV 号访问，那下一版如果暂时不能彻底搞定 BV 号的推算问题，“复制链接”是不是可以（暂时）改成 AV 号的链接【如果方便的话

可以，这次没来得及全改

**Comment by win98se** [comment]
看来有人成功搞到了AV-BV的最新转换法（已亲测正确）：https://github.com/xiaohuangren1001/Bilibili-av-bv-converter

作为参考，AV1300160740的正确BV为BV18T4m1S7iV，错误BV为BV1NQ4C1P7aN
![image](https://github.com/cotaku/Bibi-Release/assets/11819816/e47beaf6-aee2-4965-a4ee-f1e365e171c9)

**Comment by cotaku** [comment]
fixed in v3.2.17.0
