### ISSUE TITLE
昨天开始不少视频获取评论和播放出错

### ISSUE THREAD

**Issue by qakcn** [cotaku/Bibi-Release#52]
如图，无法获取评论，但标题和简介正常。

<img width="1080" alt="屏幕截图 2024-01-30 151702" src="https://github.com/cotaku/Bibi-Release/assets/1809188/c3720201-27a9-43d9-8486-84c12e3bf554">

再如图，无法获取视频地址，无法播放。

<img width="1080" alt="屏幕截图 2024-01-30 151727" src="https://github.com/cotaku/Bibi-Release/assets/1809188/8149e30a-749e-4a1e-807d-20a49a91a0a3">

但又不是全部视频都出错，有的就是正常的。

**Comment by qakcn** [comment]
出错的时候弹出的那长串数字同时出现在标题栏的AV号里，能正常播放的视频AV号是9位的，是否是AV号获取错误？

**Comment by 12345xinkai** [comment]
狗日的av号太长了，打不开了，有人必须告诉b站怎么回事来恢复av号

**Comment by 2016012036liuyun** [comment]
点了动态页面里的几个视频看了一下，貌似是1月30日中午12点以前的视频到现在也依旧可以正常看，评论区也可以正常加载，第一个无法正常浏览的视频是动态里的中午12:30左右的一个视频，从这个视频开始后面的都有问题了，评论区和动态都不行

**Comment by qakcn** [comment]
> 点了动态页面里的几个视频看了一下，貌似是1月30日中午12点以前的视频到现在也依旧可以正常看，评论区也可以正常加载，第一个无法正常浏览的视频是动态里的中午12:30左右的一个视频，从这个视频开始后面的都有问题了，评论区和动态都不行

也不是全部都有问题，还有有几个正常的，但确实大部分新的视频都出错了。不知道是不是B站改AV号的编号规则了。

**Comment by qakcn** [comment]
列几个能正常访问的给大佬参考：

1. `BV1yH4y1e7eP` / `AV1050074553`
   <img width="932" alt="屏幕截图 2024-01-31 005810" src="https://github.com/cotaku/Bibi-Release/assets/1809188/12c4d39b-e412-42ca-86ba-5a2d43307bff">

2. `BV1e5411y7Vx` / `AV454165916`
   <img width="932" alt="屏幕截图 2024-01-31 005721" src="https://github.com/cotaku/Bibi-Release/assets/1809188/048ac25f-8276-40ec-aeae-9fb3104a0bbf">

3. `BV1VH4y1v7ph` / `AV1050128949`
   <img width="931" alt="屏幕截图 2024-01-31 010214" src="https://github.com/cotaku/Bibi-Release/assets/1809188/01bb77db-3b8c-402d-93cf-7bade806c75a">

**Comment by 12345xinkai** [comment]
> > 点了动态页面里的几个视频看了一下，貌似是1月30日中午12点以前的视频到现在也依旧可以正常看，评论区也可以正常加载，第一个无法正常浏览的视频是动态里的中午12:30左右的一个视频，从这个视频开始后面的都有问题了，评论区和动态都不行
> 
> 也不是全部都有问题，还有有几个正常的，但确实大部分新的视频都出错了。不知道是不是B站改AV号的编号规则了。
> 
> 有可能能正常访问的都是早就上传好定时发布的。

定时发布的也不行

**Comment by cotaku** [comment]
fixed in [v3.2.16.0](https://github.com/cotaku/Bibi-Release/releases/tag/v3.2.16.0)
