### ISSUE TITLE
没有Arm版了吗

### ISSUE THREAD

**Issue by Jamesjili** [cotaku/Bibi-Release#54]
毕竟Arm版也有那个不能播放新视频的bug
不过如果作者放弃给手机版维护了也不是不能接受吧

**Comment by cotaku** [comment]
VS2022已经不能编译ARM版了，需要用VS2017来做，但是最近总出问题没法打包，等解决之后会继续发布ARM版。

**Comment by cotaku** [comment]
传了一个UWP_3.2.16.0_ARM.appx，不过没在实机上测试，不确定能不能用

**Comment by Jamesjili** [comment]
成功安装了，目前没有遇到Bug🥳

**Comment by yushunqwq** [comment]
成功安装，windows phone实机测试可以正常使用
![Fantasia Painting](https://github.com/cotaku/Bibi-Release/assets/77275360/22f1d970-95ed-4da6-96d1-18e84e441de2)
