### ISSUE TITLE
#部分视频仍然无法下载或观看#by版本3.2.15.0正式版

### ISSUE THREAD

**Issue by MrDeepCN** [cotaku/Bibi-Release#55]
点进去视频仍然没有播放选项，且无法下载（其表现形式和视频下架的界面相同），但是有评论区；在网页版bilibili该视频可以观看

**Comment by MrDeepCN** [comment]
更改，版本下错了，不知道为什么我下的3.2.16.0的安装包，给我装的15.0，需要重新安装才行
视频下载问题已解决
十分感谢作者的付出(´▽`ʃ♡ƪ)

**Comment by MrDeepCN** [comment]
补充，安装16.0后设置会被重置，需重新设置

**Comment by cotaku** [comment]
偷偷在商店里创建了个新应用，想看看能不能混进去重新上传一下，没注意本地打包的app名也给换了（逃

**Comment by cotaku** [comment]
fixed in v3.2.17.0
