### ISSUE TITLE
16版本手机端缺依赖包，无法安装。

### ISSUE THREAD

**Issue by feiruixin** [cotaku/Bibi-Release#56]
.net core runtime 1.1

**Comment by yushunqwq** [comment]
点下面下载，然后把.txt后缀删掉即可
[Microsoft.NET.CoreRuntime.1.1.appx.txt](https://github.com/cotaku/Bibi-Release/files/14119207/Microsoft.NET.CoreRuntime.1.1.appx.txt)

**Comment by feiruixin** [comment]
多谢

**Comment by cotaku** [comment]
现在可以从商店下载了
