### ISSUE TITLE
直播无法观看

### ISSUE THREAD

**Issue by HCLonely** [cotaku/Bibi-Release#6]
V3.2.11.0版本
![image](https://github.com/cotaku/Bibi-Release/assets/26346802/cde9ec1c-f256-4440-8734-3e91934ebdf7)

**Comment by cotaku** [comment]
这类直播问题大概解决不了，因为我这边没法复现，感觉应该是由于不同地域获得的playurl的CDN不同导致的。

**Comment by DCxDESIGN** [comment]
> 这类直播问题大概解决不了，因为我这边没法复现，感觉应该是由于不同地域获得的playurl的CDN不同导致的。

提供日志之类的会有所帮助吗？我这里也是一样的问题，移动宽带

![image](https://github.com/cotaku/Bibi-Release/assets/48208459/f9ec294e-ae09-44cd-9ab5-19921c46144c)

**Comment by cotaku** [comment]
以前已经分析过很多相关的日志了，结论就是没救（捂脸），我觉得唯一的办法就是在你电脑上挂个调试器远程调试一下（逃

**Comment by HCLonely** [comment]
![image](https://github.com/cotaku/Bibi-Release/assets/26346802/cd9152ad-63cb-48d3-810b-b96447eaf844)
试了一下playurl加Referer请求头可以获取到响应流，不加就是403。不知道是不是这个原因

**Comment by bakabaka2333** [comment]
> 我加了Referer的： 要么就是Referer的url和以前不一样了，我下个版本更新一下再试试。`PlaylistNetworkConfigs config = new PlaylistNetworkConfigs { HttpUserAgent = HttpHeaderBuilder.AndroidPlayerUserAgent, HttpReferer = url, HttpCookie = string.Empty, DownloadRetryOnFail = true };`

账户密码登录后亲测可用
扫码登录直播就不行
![Snipaste_2023-09-19_11-22-32](https://github.com/cotaku/Bibi-Release/assets/45543164/ab78aa86-6a3b-44a9-b90e-020e7003652f)

**Comment by cotaku** [comment]
flv直播总是不太行，有空研究一下更换直播源
