### ISSUE TITLE
怎么下载到xbox？

### ISSUE THREAD

**Issue by durjgdjajqsbdbfj** [cotaku/Bibi-Release#62]
如标题所述，官方版本已经停止维护，没有办法登录正常使用，问了一下，别人说这个版本可以正常使用登录，但我不知道该怎么下载

**Comment by cotaku** [comment]
见https://github.com/cotaku/Bibi-Release/discussions/61

**Comment by durjgdjajqsbdbfj** [comment]
感谢！
