### ISSUE TITLE
视频无法加载，无法登录

### ISSUE THREAD

**Issue by ymltsh** [cotaku/Bibi-Release#64]
无法加载
![image](https://github.com/cotaku/Bibi-Release/assets/100953046/27a5d473-ed26-44b2-a50b-91eeb0c397c1)
无法登录
![image](https://github.com/cotaku/Bibi-Release/assets/100953046/436ab2e2-10e2-4cfe-987d-0b6e60d30bf7)

**Comment by cotaku** [comment]
大概率是用了那种网络代(ti)理(zi)类软件导致的
