### ISSUE TITLE
分享链接和BV号错误

### ISSUE THREAD

**Issue by benchzjb** [cotaku/Bibi-Release#70]
https://www.bilibili.com/video/BV11E4C1Z7Am显示视频不存在，实际链接为https://www.bilibili.com/video/BV1gv421y7Td，而使用AV号访问则正常

**Comment by wangnick2017** [comment]
今天同样遇到该问题

**Comment by The-Fae-Sorceress** [comment]
大概是算法对于过大的av号就失效了叭，之前看网友提到了[这个](https://github.com/SocialSisterYi/bilibili-API-collect/pull/857/commits/5c75956bfaff9a060dd199df99bc38080e5708e3)

**Comment by cotaku** [comment]
fixed in v3.2.17.0
