### ISSUE TITLE
账密扫码皆不能登录

### ISSUE THREAD

**Issue by Elaman0117** [cotaku/Bibi-Release#72]
账密登录显示如下错误
![屏幕截图(7)](https://github.com/cotaku/Bibi-Release/assets/86803919/624a5169-2d00-44ba-bb32-a298f2257f39)
但也无法扫码登陆，而且是二维码本身没办法被识别

**Comment by YFTX2015** [comment]
自从本人使用微软商店版以来，账号登录就重来没有成功过，老是出现错误代码。不过扫码倒是一直都能顺利登录。说到这里，既然账号无法登录，那说明开发者没能力解决这个问题，还不如干脆把这个功能给关闭，只保留扫码多好。

**Comment by cotaku** [comment]
> 那就说明开发者没能力或者不屑解决这个问题，还不如干脆把这个功能给关闭，只保留扫码多好。

我和我的小伙伴们一直都在用密码登录，这个登不上去你要怪b站的奇葩风控啊……

**Comment by DCxDESIGN** [comment]
> 自从本人使用微软商店版以来，账号登录就重来没有成功过，老是出现错误代码。不过扫码倒是一直都能顺利登录。说到这里，既然账号无法登录，那就说明开发者没能力或者不屑解决这个问题，还不如干脆把这个功能给关闭，只保留扫码多好。

如果一直不能用密码登录，试试在网页版登录后更改一下密码，哪怕再多改一次改回原来的也行，之后就能在客户端用密码登录了，这个是B站风控，跟作者没关系

**Comment by YFTX2015** [comment]
> > 自从本人使用微软商店版以来，账号登录就重来没有成功过，老是出现错误代码。不过扫码倒是一直都能顺利登录。说到这里，既然账号无法登录，那就说明开发者没能力或者不屑解决这个问题，还不如干脆把这个功能给关闭，只保留扫码多好。
> 
> 如果一直不能用密码登录，试试在网页版登录后更改一下密码，哪怕再多改一次改回原来的也行，之后就能在客户端用密码登录了，这个是B站风控，跟

> > 那就说明开发者没能力或者不屑解决这个问题，还不如干脆把这个功能给关闭，只保留扫码多好。
> 
> 我和我的小伙伴们一直都在用密码登录，这个登不上去你要怪b站的奇葩风控啊……
虽然我搞不懂b站的这个奇葩风控是怎么回事，不过看来的确是我误会你了，不好意思了哈！再麻烦你顺便看看我提的其它问题哈！

**Comment by YFTX2015** [comment]
> > 自从本人使用微软商店版以来，账号登录就重来没有成功过，老是出现错误代码。不过扫码倒是一直都能顺利登录。说到这里，既然账号无法登录，那就说明开发者没能力或者不屑解决这个问题，还不如干脆把这个功能给关闭，只保留扫码多好。
> 
> 如果一直不能用密码登录，试试在网页版登录后更改一下密码，哪怕再多改一次改回原来的也行，之后就能在客户端用密码登录了，这个是B站风控，跟作者没关系

亲测有效，多谢！
