### ISSUE TITLE
v3.2.17的ARM版本最低版本要求怎么变成16299了？

### ISSUE THREAD

**Issue by fengfeng121380** [cotaku/Bibi-Release#73]
是编译打包的时候弄错了吗？还是放弃手机了？
![Uploading 屏幕截图 2024-03-02 140748.png…]()
![Uploading 6271554651014936652_121.jpg…]()

**Comment by fengfeng121380** [comment]
![6271554651014936652_121](https://github.com/cotaku/Bibi-Release/assets/102534883/d9f9a982-9ab2-49e7-9a49-18cffa445974)
![屏幕截图 2024-03-02 140748](https://github.com/cotaku/Bibi-Release/assets/102534883/21b74593-032c-4c08-868e-55e8d75deca4)

**Comment by cotaku** [comment]
汗，打包时候忘改了，下次版本改过来（逃

**Comment by swift-lee** [comment]
store.rg-adguard.net 也抓不到.17的arm包，不会和这个有关系吧（

**Comment by Baka632** [comment]
> 汗，打包时候忘改了，下次版本改过来（逃

@cotaku 
其实，可以给 `Package.appxmanifest` 添加一个 `<TargetDeviceFamily Name="Windows.Mobile" MinVersion="10.0.15063.0" MaxVersionTested="10.0.15254.0" />`，这样就不用手动改了（）

**Comment by see-sea7** [comment]
等不及新版本了，手动解包后修改了AppxManifest.xml文件里的MinVersion值，再用WSAppBak重新打包，ARM版终于能在我的Lumia950XL上继续使用了
[Uploading UWP_3.2.17.0_ARM.zip…]()

**Comment by yang1206** [comment]
> 等不及新版本了，手动解包后修改了AppxManifest.xml文件里的MinVersion值，再用WSAppBak重新打包，ARM版终于能在我的Lumia950XL上继续使用了 Uploading UWP_3.2.17.0_ARM.zip…

老哥是不是文件没上传成功

**Comment by swift-lee** [comment]
> > 等不及新版本了，手动解包后修改了AppxManifest.xml文件里的MinVersion值，再用WSAppBak重新打包，ARM版终于能在我的Lumia950XL上继续使用了 Uploading UWP_3.2.17.0_ARM.zip…
> 
> 老哥是不是文件没上传成功

对的，发太急了，文件还没传完。不过你可以考虑自己去搞一个 https://github.com/Wapitiii/WSAppBak

**Comment by yang1206** [comment]
> 10.0.15254.0
嗯嗯，我弄了一个，
[UWP_3.2.17.0_ARM__.zip](https://github.com/cotaku/Bibi-Release/files/15047512/UWP_3.2.17.0_ARM__.zip)

**Comment by see-sea7** [comment]
> > 等不及新版本了，手动解包后修改了AppxManifest.xml文件里的MinVersion值，再用WSAppBak重新打包，ARM版终于能在我的Lumia950XL上继续使用了 Uploading UWP_3.2.17.0_ARM.zip...
> 
> 老哥是不是文件没上传成功

还真的是，不好意思，头一次回复发文件，不过老哥你已经弄出来了

**Comment by cnbillsomeday** [comment]
> > 10.0.15254.0
> > 嗯嗯，我弄了一个，
> > [UWP_3.2.17.0_ARM__.zip](https://github.com/cotaku/Bibi-Release/files/15047512/UWP_3.2.17.0_ARM__.zip)

![image](https://github.com/cotaku/Bibi-Release/assets/43331044/43ad1b75-b4ad-4701-a7b2-390af2977bbe)
用刷机迷报错，机型lumia950XL

**Comment by see-sea7** [comment]
> > > 10.0.15254.0
> > > 嗯嗯，我弄了一个，
> > > [UWP_3.2.17.0_ARM__.zip](https://github.com/cotaku/Bibi-Release/files/15047512/UWP_3.2.17.0_ARM__.zip)
> 
> ![image](https://private-user-images.githubusercontent.com/43331044/326183099-43ad1b75-b4ad-4701-a7b2-390af2977bbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MDEyMDEsIm5iZiI6MTcxNDQwMDkwMSwicGF0aCI6Ii80MzMzMTA0NC8zMjYxODMwOTktNDNhZDFiNzUtYjRhZC00NzAxLWE3YjItMzkwYWYyOTc3YmJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE0MjgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhMTVmMmVlMDgyNjYwZjRmMmY4N2FjYmZjMTFiYmFjYjVkZTAwMmI5NTI5YjkyNjRkZTMzNjhjMjc3M2U2OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WvvkzV2SExYPMepMM2W-2lTKeaEjlz-AZPMF25Tv9VY) 用刷机迷报错，机型lumia950XL

导入手机直接安装可以
