### ISSUE TITLE
杜比视界缓存完，如果合成视频画面就会变成绿粉的，不合成就是正常的。

### ISSUE THREAD

**Issue by spromaxultra** [cotaku/Bibi-Release#75]
视频和音频合成完，颜色不正确
![image](https://github.com/cotaku/Bibi-Release/assets/160609279/399d8f59-22de-466e-bb18-24184efdaa79)
![image](https://github.com/cotaku/Bibi-Release/assets/160609279/484acf04-a62b-4491-9aa2-719435ca09cc)
不合成，颜色正确，截图有点过曝
![image](https://github.com/cotaku/Bibi-Release/assets/160609279/2587f043-ed55-439f-962f-2d5088008008)

**Comment by cotaku** [comment]
提供一下视频id

**Comment by spromaxultra** [comment]
av1300578906/BV1hu4m1P7Mu
影视飓风的
补充下，杜比视界补丁已安装，不进行合成，下面进度条预览颜色不对，上面的颜色是正确的
![image](https://github.com/cotaku/Bibi-Release/assets/160609279/eb1ad41a-28d6-4fa9-bb6e-4bee79072a4e)
不合成其他软件打开颜色正确，音视频合成后其他软件打开也不正确

**Comment by cotaku** [comment]
杜比视界这个目前不打算支持了，实在需要的话可以不合成下载然后用ffmpeg手动合成吧……
