### ISSUE TITLE
有些视频无法浏览，点击右下角访问网页版链接的地址是https://www.bilibili.com/video/BV1gc4C1A7Ng，不对，正确的是https://www.bilibili.com/video/BV1vj421U7uE/?spm_id_from=333.337.search-card.all.click，还有这个https://www.bilibili.com/video/BV1hu4m1P7Mu/?spm_id_from=333.337.search-card.all.click，另外杜比视界选项显示未知清晰度

### ISSUE THREAD

**Issue by noFinder** [cotaku/Bibi-Release#76]
![PixPin_2024-03-04_23-38-07](https://github.com/cotaku/Bibi-Release/assets/79367599/df26f295-a050-4ee9-9446-a71187347063)
![image](https://github.com/cotaku/Bibi-Release/assets/79367599/de3fbdf0-83eb-424a-9795-2dcb4a2a279a)
![image](https://github.com/cotaku/Bibi-Release/assets/79367599/54fe1fdf-73e6-47aa-9aa8-5607ba9870fc)

**Comment by cotaku** [comment]
这个视频是从哪里点进去的？直接搜索av号出来的bv号是正确的

**Comment by noFinder** [comment]
> 这个视频是从哪里点进去的？直接搜索av号出来的bv号是正确的

推荐右下角搜索关键字：诚意不足的半桶水旗舰，杜比视界
![recording](https://github.com/cotaku/Bibi-Release/assets/79367599/58204965-b29f-45e6-8a22-e102ad0f2550)
![recording](https://github.com/cotaku/Bibi-Release/assets/79367599/bd957897-1a08-4b5a-9b8a-ed4ec7159def)

**Comment by noFinder** [comment]
> 这个视频是从哪里点进去的？直接搜索av号出来的bv号是正确的

还有有的首页推荐
![recording](https://github.com/cotaku/Bibi-Release/assets/79367599/000fcf60-3a7b-4512-ba24-d01f3a49e669)

**Comment by cotaku** [comment]
应用是最新版吗？最新版并没发现这个问题
