### ISSUE TITLE
请问是否还兼容lumia的wp系统？

### ISSUE THREAD

**Issue by nahco365** [cotaku/Bibi-Release#77]
前阵子想在wp上用哔哩哔哩uwp，但是官方原版的已经不能正常使用了。想用这个安装试试，但是在Lumia内打开只有安装确认不能真的安装，于是特地来问一下。

**Comment by nahco365** [comment]
尝试了一下，3.2.14版本是可以安装使用的，3.2.15没有ARM版本，3.2.16版本开始安装会报错

**Comment by nahco365** [comment]
这样也不错了，谢谢暗影大佬！！！

**Comment by cotaku** [comment]
最新版忘改ARM版的OS版本要求了，下个版本会修正就可以正常安装了

**Comment by nahco365** [comment]
好耶！

**Comment by see-sea7** [comment]
等不及新版本了，手动解包后修改了AppxManifest.xml文件里的MinVersion值，再用WSAppBak重新打包，ARM版终于能在我的Lumia950XL上继续使用了
[Uploading UWP_3.2.17.0_ARM.zip…]()

**Comment by nahco365** [comment]
> 等不及新版本了，手动解包后修改了AppxManifest.xml文件里的MinVersion值，再用WSAppBak重新打包，ARM版终于能在我的Lumia950XL上继续使用了 Uploading UWP_3.2.17.0_ARM.zip…

太好了！谢谢你！（迫不及待的搓手）

**Comment by see-sea7** [comment]
> > 等不及新版本了，手动解包后修改了AppxManifest.xml文件里的MinVersion值，再用WSAppBak重新打包，ARM版终于能在我的Lumia950XL上继续使用了 Uploading UWP_3.2.17.0_ARM.zip…
> 
> 太好了！谢谢你！（迫不及待的搓手）

[UWP_3.2.17.0_ARM.zip](https://github.com/cotaku/Bibi-Release/files/15048758/UWP_3.2.17.0_ARM.zip)
