### ISSUE TITLE
为啥下载相同资源，uwp版下载下来的文件体积要比exe版下载下来的小很多？

### ISSUE THREAD

**Issue by YFTX2015** [cotaku/Bibi-Release#78]
视频清晰度、码率等是否打了折扣？

**Comment by cotaku** [comment]
举个栗子？

**Comment by YFTX2015** [comment]
比如这个：【【圣兽之王】4K 最高画质 全流程通关攻略 香草社策略战棋游戏 - Unicorn Overlord】 https://www.bilibili.com/video/BV1nC411p7N2/?share_source=copy_web&vd_source=b5e478714ff2da3589bae6739300a23f。这种单文件体积比较大的差距会很明显。

**Comment by YFTX2015** [comment]
有以下区别：一、文件格式不同，uwp版合并后为mp4，exe版为m4s，官方不提供合并。二、文件大小不同。uwp版下载下来的文件普遍小于uwp版。三、是否加密，uwp版目前未加密（曾经加密过一段时间），exe版始终加密。

**Comment by RedVelvet2014** [comment]
会不会是你开了hevc

**Comment by cotaku** [comment]
另外可以比较一下码率，同样是1080p但是有高低两种码率，exe下的可能是低码率版

**Comment by YFTX2015** [comment]
确实开了hevc，难道这个会缩减体积？由于我是大会员，两个版本下载的时候默认选的都是最高码率.。

**Comment by cotaku** [comment]
> 确实开了hevc，难道这个会缩减体积？

会的，相同画质下一般hevc比h264小一些

**Comment by RedVelvet2014** [comment]
> 确实开了hevc，难道这个会缩减体积？由于我是大会员，两个版本下载的时候默认选的都是最高码率.。

b的hevc的码率低到爆，导致清晰度也大减，我之前整理的时候才发现

**Comment by YFTX2015** [comment]
果真如此，关了体积几乎增加一倍。不如干脆把这个选项取消算了，免得又有像我一样搞不清楚的人误选。

**Comment by YFTX2015** [comment]
> > 确实开了hevc，难道这个会缩减体积？由于我是大会员，两个版本下载的时候默认选的都是最高码率.。
> 
> b的hevc的码率低到爆，导致清晰度也大减，我之前整理的时候才发现

近两年，阿b不管是国区，还是港澳台地区，乃至东南亚区，番剧体积都大幅缩减，估计码率也都大幅下降。几年前，下载一集1080p的1g左右，现在普遍一两百m。在线能够始终保持高码率的，我看也就只有hamivideo、cr之类的了。
