### ISSUE TITLE
番剧入口播放失败

### ISSUE THREAD

**Issue by komiblog** [cotaku/Bibi-Release#8]
在“追番”界面下，点击“我的追番”里的番剧，会出现如下播放失败字样：

![image](https://github.com/cotaku/Bibi-Release/assets/102006886/1874f692-2289-43c3-916d-3c6187587da4)

![image](https://github.com/cotaku/Bibi-Release/assets/102006886/e54d60f4-3a02-4f25-a61a-0337e2de1ab9)

通过搜索搜出番剧，再点击播放，可以正常播放。

希望能修复这个bug

**Comment by cotaku** [comment]
下次更新会修复

**Comment by komiblog** [comment]
好的，非常感谢

**Comment by cotaku** [comment]
fixed in v3.2.12.0
