### ISSUE TITLE
uwp版下载速度问题

### ISSUE THREAD

**Issue by YFTX2015** [cotaku/Bibi-Release#80]
高的时候也就几十兆每秒，始终无法跑满带宽，不管用不用代理，而且速度还不稳定，慢的时候，甚至只有几百K每秒。而用idm下载网页端嗅探出来的视频，普遍都能满速下载，还不掉速，这点能否改善？

**Comment by cotaku** [comment]
在线播放和下载的地址是不同的，如果用播放用地址来下载的话会有很多很难处理的问题，比如地址会不停过期更换，而且下载地址根据环境的不同返回的DNS也不同，下载速度也会被服务器限制，应用本身是没有任何限速的。

**Comment by YFTX2015** [comment]
既然应用本身没限速的话，那多半就跟下载线程数有关了。我估计uwp跟exe客户端都不支持多线程下载，即使支持，应该也没有idm线程数那么多。

**Comment by YFTX2015** [comment]
好

**Comment by YFTX2015** [comment]
在uwp版里面用右键获取的下载链接跟在网页端里面用浏览器开发者工具获取的下载链接一致。这种链接只有在片源是港澳台地区并且搭梯子的时候才能被idm识别，只要是国内片源通通识别不了。用idm在网页端嗅探的时候应该是对下载地址进行了转换，用原始地址根本下不下来，多半是加了密的。
