### ISSUE TITLE
刷新动态时在加载一些视频后显示“获取关注动态失败”

### ISSUE THREAD

**Issue by wangnick2017** [cotaku/Bibi-Release#82]
3.2.17 x64版
动态界面，每次点击刷新后，会加载出一系列视频（大部分时候能填满整个屏幕），然后跟随着显示一个错误窗口。虽然一般加载出来的视频数量已经足够看最新的动态了，但每次都要点一下关闭这个错误窗口有点难受
<img width="520" alt="%7BDF322935-07D6-43c3-90D4-A3DCA7A1FC43%7D" src="https://github.com/cotaku/Bibi-Release/assets/33253388/45cb0e50-3097-4d57-a1f7-b7f07cfc09e6">

**Comment by cotaku** [comment]
是有这个问题，可能是因为后台刷新太快，我稍微调整一下

**Comment by cotaku** [comment]
mitigated in v3.3.1.0
