### ISSUE TITLE
账密不可登录

### ISSUE THREAD

**Issue by 318cyz** [cotaku/Bibi-Release#83]
rt，返回的数据是风控验证码页面（scene=deviceVerify），建议加上对该验证的支持。

另外最新的 ARM release 包在更新到最新版本 1709 的 Lumia 950 上提示不满足最低系统版本要求（从之前的 10.0.15063.0 提高到了 10.0.16299.0），请求修复。

————~~~~

**Comment by cotaku** [comment]
可参考：
https://github.com/cotaku/Bibi-Release/issues/72#issuecomment-1974263814
https://github.com/cotaku/Bibi-Release/issues/77#issuecomment-1987335160

**Comment by cotaku** [comment]
mitigated in v3.3.1.0
