### ISSUE TITLE
可以添加B站ai助手吗

### ISSUE THREAD

**Issue by ZJH365** [cotaku/Bibi-Release#85]
本人也是uwp，winui3，wpf开发者，winui3代码大部分应该可以很轻易的移植到uwp，没有源代码所以不知道移植难度咋样，不过应该不难。参考这个：https://www.github.com/BlameTwo/BiliStart.WinUI3-Preview?tab=readme-ov-file

**Comment by cotaku** [comment]
基本上不考虑添加这种花哨功能……
