### ISSUE TITLE
现在升级v3.2.17.0和之前的v3.2.16.0版本以后，uwp版本一直无法正常使用

### ISSUE THREAD

**Issue by caoymq** [cotaku/Bibi-Release#86]
现在升级v3.2.17.0和之前的v3.2.16.0版本以后，uwp版本一直无法正常使用，不管是从商店安装的版本，还是下载后安装证书和安装包的版本，总是安装完可以打开软件界面，在主界面里面点击下面的视频总是没反应，不会进入视频的下一个界面，点击直播区域的可以进入下一个界面，退出软件后就在开始菜单里面点不开软件了，必须要进应用的界面重置一下，但是还是不能在点开视频播放，喜欢用这个软件，被困扰很久了，希望可以看下什么原因
操作系统版本
Microsoft Windows 11 专业工作站版 (64 位) 23H2 (10.0.22631)
cpu：R9 5950X
gpu：rtx 3060
内存：32G

![IMG_6796](https://github.com/cotaku/Bibi-Release/assets/166041265/8e01c87c-65b1-47be-8a93-417b1c3b06ca)

**Comment by cotaku** [comment]
3.2.16.0以前的版本没有问题？

**Comment by caoymq** [comment]
对，3.2.15.0之前的版本版本打开都没这些问题，后面因为那个av还是bv号长度超过以后，无法播放新视频，然后更新软件以后，就这样了，很抓狂

**Comment by caoymq** [comment]
升级到v3.3.0.0版本以后可以正常使用了
