### ISSUE TITLE
直播还是看不了 v3.2.17.0版本

### ISSUE THREAD

**Issue by ghvencose** [cotaku/Bibi-Release#88]
![QQ图片20240408092916](https://github.com/cotaku/Bibi-Release/assets/166348403/55784aef-3f1a-4701-acc0-c1f490f44b92)

**Comment by ghvencose** [comment]
真的没办法修复嘛：(

**Comment by cotaku** [comment]
不想花时间修，无限期搁置中（逃

**Comment by Liuyiyang888888** [comment]
可不可以修一下

**Comment by cotaku** [comment]
弹幕估计修不好了，只能发不能收，WebSocket一连就直接被断掉，心累……

**Comment by cotaku** [comment]
fixed in v3.3.1.0
