### ISSUE TITLE
无法登录了

### ISSUE THREAD

**Issue by RedVelvet2014** [cotaku/Bibi-Release#9]
二维码登录则显示二维码异常
![屏幕截图 4](https://github.com/cotaku/Bibi-Release/assets/145118561/f0659db1-81b7-4189-8dc0-9385c6a30766)

**Comment by dustinthesky** [comment]
我也是，刚才不能登录了，密码登录也会报错
![image](https://github.com/cotaku/Bibi-Release/assets/52279232/df934828-2b30-4311-b7c7-6dd5856d2579)

**Comment by cotaku** [comment]
二维码登录已经修好了，正在全力抢修密码登录（逃

**Comment by cotaku** [comment]
密码登录也修好了，我先去喝口水（逃
![image](https://github.com/cotaku/Bibi-Release/assets/2822574/809db9fc-3ce4-494c-be19-9644849eba93)

**Comment by yurixxx** [comment]
好像还是不行？

**Comment by yurixxx** [comment]
> 密码登录也修好了，我先去喝口水（逃 ![image](https://user-images.githubusercontent.com/2822574/268484985-809db9fc-3ce4-494c-be19-9644849eba93.png)

好像还是不行？

**Comment by RedVelvet2014** [comment]
似乎还不行，刚刚尝试了两种方式登录都还是老样子

**Comment by cotaku** [comment]
> > 密码登录也修好了，我先去喝口水（逃 ![image](https://user-images.githubusercontent.com/2822574/268484985-809db9fc-3ce4-494c-be19-9644849eba93.png)
> 
> 好像还是不行？

我还没发布更新啊😂

**Comment by RedVelvet2014** [comment]
> > 好像还是不行？
> 
> 我还没发布更新啊😂

🥳大佬辛苦了

**Comment by LMDM387** [comment]
无敌的佬在6分钟前更新
