### ISSUE TITLE
CC字幕好像是没有了

### ISSUE THREAD

**Issue by GalaxyeyesTchyonDragon** [cotaku/Bibi-Release#91]
观看港澳台番剧的时候没有CC字幕，连弹幕也不显示

**Comment by GalaxyeyesTchyonDragon** [comment]
还有就是刚卸载又在这里装了最新版，现在开VPN也看不了港澳台番剧了😂

**Comment by cotaku** [comment]
我手里已经没有当地的代理服务器了，没法测试这玩意……

**Comment by GalaxyeyesTchyonDragon** [comment]
> 我手里已经没有当地的代理服务器了，没法测试这玩意……

行吧，还能用这个已经很满足了，辛苦了
