### ISSUE TITLE
关于旧版本直播无弹幕问题

### ISSUE THREAD

**Issue by bxtxssr** [cotaku/Bibi-Release#97]
由于新版本无法观看直播，目前一直在使用旧版本（v3.2.14.0）观看。之前偶发直播无法显示弹幕，在个人中心退出账号后重新登录可以变好；而最近无弹幕问题无法通过重新登录方式修复，请问有无其他解决方法？感谢！

**Comment by bxtxssr** [comment]
更新至3.3版本直播可以看了，无弹幕问题还在

**Comment by win98se** [comment]
> 更新至3.3版本直播可以看了，无弹幕问题还在

作者在#88 中提到，`弹幕估计修不好了，只能发不能收，WebSocket一连就直接被断掉`
