### ISSUE TITLE
这玩意怎么安装到wp上啊

### ISSUE THREAD

**Issue by ASF084132** [cotaku/Bibi-Release#99]
我用刷机迷安装appx显示缺少依赖包，我搞不懂缺了什么

**Comment by cotaku** [comment]
可以在商店直接安装

**Comment by ASF084132** [comment]
> 可以在商店直接安装
商店提示不支持的设备无法运行

**Comment by win98se** [comment]
> > 可以在商店直接安装

> 商店提示不支持的设备无法运行

参考#73，因为3.2.17最低版本被错误设置为制版号16299，而W10M的最新制版号是15254，所以商店装不了，暂时用安装包吧
